# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0b402m59xxna88igpb1gbpn7qm7w4h94mfpywkbyv1dgcrkqbajl";
    aarch64-linux = "0kjvq6069qwn1nxsirb32wjxmzbjg4sw1zj056pr0ykfpxks5fc3";
    x86_64-darwin = "1ni2v13i7y6z5ybbbxgv8daii38w1mjv349lj7ai8yqvfky2sc5c";
    aarch64-darwin = "0xchhc9q2v05bp9x2nibsypjsy5x975ajqm9g5cxanjjfbpjyw81";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.2.5/kubectl-netdrill_0.2.5_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.2.5/kubectl-netdrill_0.2.5_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.2.5/kubectl-netdrill_0.2.5_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.2.5/kubectl-netdrill_0.2.5_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-netdrill";
  version = "0.2.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-netdrill $out/bin/kubectl-netdrill
    installManPage manpages/kubectl-netdrill.1.gz
    installManPage manpages/kubectl-netdrill-run.1.gz
    installManPage manpages/kubectl-netdrill-pod.1.gz
    installManPage manpages/kubectl-netdrill-debug.1.gz
    installManPage manpages/kubectl-netdrill-deployment.1.gz
    installShellCompletion --cmd kubectl-netdrill \
    --bash <($out/bin/kubectl-netdrill completion bash) \
    --fish <($out/bin/kubectl-netdrill completion fish) \
    --zsh <($out/bin/kubectl-netdrill completion zsh)
  '';

  meta = {
    description = "kubectl-netdrill";
    homepage = "https://github.com/xenOs76/kubectl-netdrill";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
