# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "04mr6dgcwzcq7shqrhj8gfb3jh0inz8rr523gzhlmin9xwrhcf70";
    aarch64-linux = "1xgbf28lb8ywpq0idans6q3i3a157gv69d6qrkrlsagcw6cj1bg4";
    x86_64-darwin = "1w43hjss0pnxvf3z310ms99cdrmgqw92j7ydng056hf52rn5cj75";
    aarch64-darwin = "0n1jvgbnddr9hcdpgz555g4arwsy0z8h30f73hvg5ib569cf2g01";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.1.3/kubectl-netdrill_0.1.3_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.1.3/kubectl-netdrill_0.1.3_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.1.3/kubectl-netdrill_0.1.3_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.1.3/kubectl-netdrill_0.1.3_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-netdrill";
  version = "0.1.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-netdrill $out/bin/kubectl-netdrill
  '';

  system = system;

  meta = {
    description = "kubectl-netdrill";
    homepage = "https://github.com/xenOs76/kubectl-netdrill";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
