# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "13hsscw1znqfaqff1g43ab5cz6pq5cnk901nzgfvriinl82z05m9";
    aarch64-linux = "1d0zjvp6xrksbiw4fvx5p8ncq816k3hvwrbnxgzdamvw8f580ck5";
    x86_64-darwin = "0d2cqdsg1y9n6h66z3f1g01h1i2h1fxiyz7aqlhlvpb33dgfhf3l";
    aarch64-darwin = "0hyn2rmwyq2rc2bb9wbmavxps7wz2478y8di8bq34ic7y9aj2arb";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.0.1/kubectl-netdrill_0.0.1_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.0.1/kubectl-netdrill_0.0.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.0.1/kubectl-netdrill_0.0.1_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-netdrill/releases/download/0.0.1/kubectl-netdrill_0.0.1_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-netdrill";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-netdrill $out/bin/kubectl-netdrill
  '';

  system = system;

  meta = {
    description = "kubectl-netdrill";
    homepage = "https://github.com/xenOs76/kubectl-netdrill";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
