# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1wjqizwss2lcxll1kc5lvxfjx72gvgnv22b1y3gdg1hxdwmyszvs";
    aarch64-linux = "1b8wpj0bnpf6xjhnma6dmw3p5srb5gwkr915pz981zhm26i26zbg";
    x86_64-darwin = "0shb116g8cl1hyp297g5622rrlczr7w8vpn3db8l5byvhpv147g2";
    aarch64-darwin = "1jxfcd35inglqjcj2wlj3xlj2ajd73p5k95ykjr99dlxr4danwdj";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/aws-probe/releases/download/0.2.0/aws-probe_0.2.0_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/aws-probe/releases/download/0.2.0/aws-probe_0.2.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/aws-probe/releases/download/0.2.0/aws-probe_0.2.0_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/aws-probe/releases/download/0.2.0/aws-probe_0.2.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "aws-probe";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./aws-probe $out/bin/aws-probe
    installShellCompletion --cmd aws-probe \
    --bash <($out/bin/aws-probe completion bash) \
    --fish <($out/bin/aws-probe completion fish) \
    --zsh <($out/bin/aws-probe completion zsh)
  '';

  meta = {
    description = "aws-probe";
    homepage = "https://github.com/xenOs76/aws-probe";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
