# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0yn569v75kaflg43k7knndlhwqrsx1m66wpg3gmijbzwsgbhp16b";
    aarch64-linux = "0vki93agl6sxhvn43fyxpynqdw10sng7hdwcvgb39hhxjcmj00qb";
    x86_64-darwin = "1i18vj42q2idjwcyh12yfp55m28lr6j256cgibnj7ipk8493l3h5";
    aarch64-darwin = "0zpfjdhgqibpns67nd4dphdh991176kvbf3jmmrvndi6qzfc7qh3";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/aws-probe/releases/download/0.3.1/aws-probe_0.3.1_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/aws-probe/releases/download/0.3.1/aws-probe_0.3.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/aws-probe/releases/download/0.3.1/aws-probe_0.3.1_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/aws-probe/releases/download/0.3.1/aws-probe_0.3.1_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "aws-probe";
  version = "0.3.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./aws-probe $out/bin/aws-probe
    installShellCompletion --cmd aws-probe \
    --bash <($out/bin/aws-probe completion bash) \
    --fish <($out/bin/aws-probe completion fish) \
    --zsh <($out/bin/aws-probe completion zsh)
  '';

  meta = {
    description = "aws-probe";
    homepage = "https://github.com/xenOs76/aws-probe";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
