# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0258ks0r72hil0xj4ykqvpwad4m8i4rjz02mym5hpxsbx8l0yypn";
    aarch64-linux = "18j64ilr072fil6dk564qmjmgv6kwmm4mwqxjx7mig3qp0g8mzcb";
    x86_64-darwin = "0c1dwkljm7027ifcbskkkkpyi9mw5kvag0kcfz78y26pfla3ldng";
    aarch64-darwin = "0402mmcm4m8pjywb90krhz21jmqz6jwh1bbdhlryzrq448bc2pdx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.2.0/https-wrench_0.2.0_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.2.0/https-wrench_0.2.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.2.0/https-wrench_0.2.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.2.0/https-wrench_0.2.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "https-wrench";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./https-wrench $out/bin/https-wrench
  '';

  system = system;

  meta = {
    description = "https-wrench";
    homepage = "https://github.com/xenOs76/https-wrench";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
