# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1152bk152g3lcnf04yvqaxnrqnsd4rv8rk565sa6pk9wq72walkl";
    aarch64-linux = "09y23x2vn8zvx9dafq66g6l4k1nh75zj1am75wk2y8sb1hfhbri2";
    x86_64-darwin = "18nqryxg29jcri74qar1465828mmzbmscswi1argbvl42shrld9n";
    aarch64-darwin = "0rzb90vi8myq2lbghph52q73q67xah5gdm63vl3vjxlxk2925h7r";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.11.2/https-wrench_0.11.2_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.11.2/https-wrench_0.11.2_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.11.2/https-wrench_0.11.2_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.11.2/https-wrench_0.11.2_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "https-wrench";
  version = "0.11.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./https-wrench $out/bin/https-wrench
    installManPage manpages/https-wrench.1.gz
    installManPage manpages/https-wrench-certinfo.1.gz
    installManPage manpages/https-wrench-requests.1.gz
    installShellCompletion --cmd https-wrench \
    --bash <($out/bin/https-wrench completion bash) \
    --fish <($out/bin/https-wrench completion fish) \
    --zsh <($out/bin/https-wrench completion zsh)
  '';

  meta = {
    description = "https-wrench";
    homepage = "https://github.com/xenOs76/https-wrench";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
