# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0kddadw1xqsm6n13l2xxrqjz2sd1cpwmh7q2476j11k6rfxkj49h";
    aarch64-linux = "0alvr83j0zm3n21k1adjgvbqzfl53y2wckxlyvmmjpbgjmkk559q";
    x86_64-darwin = "1lgzj8rrdpfbw5gk0bsc9bw951s6dlzwx0rhcnwg9kypcrlvndqa";
    aarch64-darwin = "1r26dbn3h78lnaqa7anmwjsn9fr1gcwlwdf6plk0amz0w3033lix";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.1.0/https-wrench_0.1.0_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/https-wrench/releases/download/0.1.0/https-wrench_0.1.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.1.0/https-wrench_0.1.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/https-wrench/releases/download/0.1.0/https-wrench_0.1.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "https-wrench";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./https-wrench $out/bin/https-wrench
  '';

  system = system;

  meta = {
    description = "https-wrench";
    homepage = "https://github.com/xenOs76/https-wrench";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
