# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "08kj8mh0699myc5gc5gqa9j64n31r401gr21ch3pizr80mfas6gx";
    aarch64-linux = "0biiflf3qfrv4ilxa8bhg97w6nppivhjwbks5s2a8fjm3j35j3dz";
    x86_64-darwin = "0qbh1ilyqcn05fg7bv60g8wwxjrcpbshhws0mkrkn3qk8mhmzq45";
    aarch64-darwin = "05kjc16x4abdslz0gzpwk4pf9v9g0fwsmkghz7k92dw1a8lkjgg2";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.2.0/kubectl-crdlist_0.2.0_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.2.0/kubectl-crdlist_0.2.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.2.0/kubectl-crdlist_0.2.0_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.2.0/kubectl-crdlist_0.2.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-crdlist";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-crdlist $out/bin/kubectl-crdlist
  '';

  meta = {
    description = "kubectl-crdlist";
    homepage = "https://github.com/xenOs76/kubectl-crdlist";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
