# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1nqdvhsb337871zidl34wkhc06aivckkqwggyna9fzjyns0x1b0h";
    aarch64-linux = "0fdnrnr0qj9xghslg4rd8yiqgx3i4kg54wz0iqljpnzg3cp296pa";
    x86_64-darwin = "0rs82893cn21jgfxacx1azvz7iq7rl8k7jyj666q8xk3z6m839gw";
    aarch64-darwin = "1inq6v6sz5zv3v3zvhpbhzf1lgdfn7lkrb0dz4qr7yw6wfxln2v4";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.3.0/kubectl-crdlist_0.3.0_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.3.0/kubectl-crdlist_0.3.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.3.0/kubectl-crdlist_0.3.0_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.3.0/kubectl-crdlist_0.3.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-crdlist";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-crdlist $out/bin/kubectl-crdlist
  '';

  meta = {
    description = "kubectl-crdlist";
    homepage = "https://github.com/xenOs76/kubectl-crdlist";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
