# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1pk3dmx4ka63wj5wl5cyyiz924cpcb14wfglp8z54javdlxb39a8";
    aarch64-linux = "1jpdrc2y1b6k40xskhv88rphbm3z4bxq7072k566s529p4h72h60";
    x86_64-darwin = "17rv293a0ajri6qfvpy8ic7gby4kbvbijb9xshsbfzjnr4qwg2mz";
    aarch64-darwin = "08z9bhmrcc4spdn9mkwi6snc63v2b2qzypyzpshhijhki6xgsjm4";
  };

  urlMap = {
    x86_64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.1.0/kubectl-crdlist_0.1.0_Linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.1.0/kubectl-crdlist_0.1.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.1.0/kubectl-crdlist_0.1.0_Darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/xenos76/kubectl-crdlist/releases/download/0.1.0/kubectl-crdlist_0.1.0_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kubectl-crdlist";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./kubectl-crdlist $out/bin/kubectl-crdlist
  '';

  system = system;

  meta = {
    description = "kubectl-crdlist";
    homepage = "https://github.com/xenOs76/kubectl-crdlist";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
